version: '3'

services:
  wp:
    image: wordpress
    restart: always
    environment:
      DB_HOST: 192.168.99.100
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      FS_METHOD: direct
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://127.0.0.1/wp-login.php"]
      timeout: 10s
    ports:
      - "8088:8088"
    volumes:
      - /wp_content:/var/www/wp-content
    container_name: wp